name: Auto Rebase main Branch

on:
  push:
    branches:
      - plain
jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Auto Rebase main
        uses: dearfl/rebase@main
        with:
          base: plain
          branch: main
